package hello;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'aluno02' at '09/06/15 13:12' with Gradle 2.4
 *
 * @author aluno02, @date 09/06/15 13:12
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
